# Generated by Django 2.0.1 on 2018-02-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='parent_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='groups.UserGroup'),
        ),
    ]
