# Generated by Django 2.0.1 on 2018-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180205_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
