# Generated by Django 2.0.2 on 2018-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=30)),
                ('url', models.CharField(default='', max_length=7)),
            ],
        ),
    ]
