# Generated by Django 2.0.2 on 2018-02-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
