# Generated by Django 2.0.2 on 2018-03-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_course', '0003_auto_20180226_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRepositoryUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ip', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('updated', models.BooleanField(default=False)),
                ('log', models.TextField(default='')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='manage_course.CourseRepository')),
            ],
        ),
    ]
